version: '3.3'

services:

  qgisserver:
      image: "camptocamp/qgis-server:3.10"
      volumes:
          - ../data:/etc/data
          - ./qgis_projects:/etc/qgisserver      
      ports:
          - "8380:80"
      environment:
          - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgs

