version: '3.8'

services:

  qgisserver:
      container_name: "ogc_qgisserver"
      image: "camptocamp/qgis-server:3.16"
      volumes:
          - ../data:/etc/data
          - ./qgis_projects:/etc/qgisserver      
      ports:
          - "80:80"
      environment:
          - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgs
      restart: always
