version: '3.8'

services:

  qgisserver:
      container_name: "ogc_qgisserver"
      image: "openquake/qgis-server:3.16.3"
      volumes:
          - ../data:/etc/data
          - ./qgis_projects:/etc/qgisserver      
          - ${HOME}/.pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
      ports:
          - "80:80"
      environment:
          - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgs
          - SKIP_NGINX=false
      restart: always
