version: '3.8'

services:

  qgisserver:
      container_name: "ogc_qgisserver"
      image: "camptocamp/qgis-server:3.22"
      volumes:
          - ../data:/etc/data
          - ./qgis_projects:/etc/qgisserver      
          - ${HOME}/.pg_service.conf:/etc/qgisserver/pg_service.conf:ro
      ports:
          - "80:80"
      environment:
          - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgs
          - PGSERVICEFILE=/etc/qgisserver/pg_service.conf
          - QGIS_SERVER_LOG_LEVEL=1
      restart: always
      network_mode: "host"

